### ISSUE TITLE
add more Information to the Form 

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#10]
## Value Proposition
As a user,
I want to add more Information to the form
so that I can repeat habits more often .

## Description

![Screenshot 2022-10-23 at 23 14 12](https://user-images.githubusercontent.com/111757889/197418797-345be4f1-fcd5-43de-86cf-a47346f837fa.png)

## Acception Criteria
- [x] as a user, I want to add detailed Information to my habit 
- [x] as a user, I want to add the frequency of my habit
- [x]  as a user, I want to add the Daytime (All Day, Morning, Afternoon, Evening, Night) of my habit
- [x] as a user, I want to add the starting date of my habit
## Tasks
- [x] create a new branch `add detailed Information`
- [x] create `Input component` for `describe` (input field type = "text")
- [x] create `Input component` for `frequency` (input field type = "checkbox")
- [x] able to click between `Daily, Weekly, Monthly`
- [x] create `Input component`  for `DayTime`(input field type = "checkbox")
- [x] able to click between `All Day, Morning, Afternoon, Evening, Night`
- [x] create  `Input component`  for `Calendar`(input field type = "date")
- [x] create styled component for each Inputbox

**Comment by AHen-C0de** [comment]
Hey,
this is a nice and clear user story. Some suggestions from my side:
- looks like you have 3 different forms of input fields (text, checkbox and date), so you could create only 3 different input components and re-use them
- according to that, I would add the type of input field you want to use
- I would summarise the last three bullet points to "add information `describe`, `frequency` and `DayTime` to Array in db.js"
  - you could also add one more sentence about how you are going to do this

**Comment by Sukhpreet92** [comment]
> Hey, this is a nice and clear user story. Some suggestions from my side:
> 
> * looks like you have 3 different forms of input fields (text, checkbox and date), so you could create only 3 different input components and re-use them
> * according to that, I would add the type of input field you want to use
> * I would summarise the last three bullet points to "add information `describe`, `frequency` and `DayTime` to Array in db.js"
>   
>   * you could also add one more sentence about how you are going to do this

Thank you @AHen-C0de  i have made the changes according to your suggestions.
