### ISSUE TITLE
Mongo DB

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#14]
## Value Proposition
As a user, 
I want to save my data
so that i can recall them again.
## Description
no Wire Frame
## Acception Criteria
- [ ] create connection to MongoDB 
- [ ] save in DB `Habit,  frequency, Daytime, starting date `

## Tasks
- [x]  new branch `connect MongoDB`
- [x] `npm i mongoose`
- [x]  Create .env.local file and add MongoDB Atlas Link
- [x] Create a /lib/dbConnect.js
- [x]  Import Data into Database without ID's
- [x] create models folder and create new Schema
- [x] write async function getServerSideProps in index.js
- [x] delete fake db from lib
