### ISSUE TITLE
Navigation 

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#15]
## Value Proposition
As a user, I want to switch between home and the add page
so that so i can see switch between pages..
## Description

![Screenshot 2022-10-31 at 00 28 23](https://user-images.githubusercontent.com/111757889/198907142-975a4ef3-63ae-4932-b720-6845147e8f66.png)

## Acception Criteria
- [x] display Navi-Bar
- [x] Navi-button for each page
- [x] able to switch between home and add page
- [x] Header and bar will be able to see in both pages
## Tasks
- [x] create new branch called `navigation_bar`
- [x] create Layout component
- [x] create each navigation entry as `button component` (li within ul)
- [x] add some styling with `styled component`

**Comment by CathrinTruchan** [comment]
You could also add a task for creating the layout component? Or how do you implement the navbar on each page?

**Comment by Sukhpreet92** [comment]
> You could also add a task for creating the layout component? Or how do you implement the navbar on each page?

Thank you i missed that step.
