### ISSUE TITLE
Add categories

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#19]
## Value Proposition
As a user, I want switch between daytime so that I can see what I have planned e.g. in the evening.
## Description
![Screenshot 2022-11-02 at 09 26 41](https://user-images.githubusercontent.com/111757889/199468435-9b4ebb50-ceed-44e7-973e-0c750134bffc.png)
![Screenshot 2022-11-02 at 09 27 09](https://user-images.githubusercontent.com/111757889/199468441-bc84a8f4-e0bc-483b-bf35-97d735765fbf.png)

## Acception Criteria
- [ ] able to switch between `All-day` `Morning` `Afternoon` `Evening` `Night` 
- [ ] able to click multiply daytime
- [ ] show the habits under each criteria 

## Tasks
- [ ] create new branch 
- [ ] create `components` for `All-day` `Morning` `Afternoon` `Evening` `Night` 
- [ ] add .filter() to components
- [ ] add categories to the DB

```
[
  {
    id: nanoid(),
    name: "All-day",
  },
  {
    id: nanoid(),
    name: "Morning",
  },
];
.
.
.
