### ISSUE TITLE
User Story for habit list display

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#2]
## Value Proposition
As a user, I want to have a view of my habit, so I can keep a track of it.

## Description

![Screenshot 2022-10-17 at 16 13 37](https://user-images.githubusercontent.com/111757889/196200199-0b00d8dd-9a2d-43f6-a6c8-0de49ff62758.png)

## Acception Criteria
- [x] as a user I want to have list of All Day doings displayed 
- [x] as a user I want to list them under AllDay

## Tasks
- [x] new branch
- [x] create a Headline `All Day`
- [x] create a list for daily habits

**Comment by F-Kirchhoff** [comment]
Hey Sukhpreet, this is already looking quite good, but unfortunately this user story starts somewhere in the middle of your App development process. Why is there a navigation bar? Where does the list of habits come from? There are a lot of features that you don't need at first. Ask you the one question: What is the most basic feature of your App? Then create a user story which includes only that feature (a feature can also be displaying something).

**Comment by gacsphere** [comment]
Hi Sukhpreet, is it one button for `integrate/break` and the next step would be to choose if you integrate or break the habit? Then it seems right to me. I think you would set the habit then in the third step, right?

**Comment by Sukhpreet92** [comment]
> Hi Sukhpreet, is it one button for `integrate/break` and the next step would be to choose if you integrate or break the habit? Then it seems right to me. I think you would set the habit then in the third step, right?

Yes Gesa, actually I am confused. I am not sure should I create a list to add the habit or a pop up so that user can enter by them self.

**Comment by F-Kirchhoff** [comment]
Hey Sukhpreet, do you really need this extra page? I guess you can add these features into your main page for now. A welcome page is only necessary if you have already a lot of content in your app, for now it would feel like an unnecessary extra step for the users.

**Comment by gacsphere** [comment]
Now I'm also a bit confused. :sweat_smile:

To your question:
I would say the user wants to enter his own issues. But that's not happening in this screen. It might be a future step.

**Comment by Sukhpreet92** [comment]
> Hey Sukhpreet, do you really need this extra page? I guess you can add these features into your main page for now. A welcome page is only necessary if you have already a lot of content in your app, for now it would feel like an unnecessary extra step for the users.

Hey Felix,  I am really confuses now. Can you please check if this is fine ? I would start with the Homepage with the list able to be add on it.

**Comment by Sukhpreet92** [comment]
> Now I'm also a bit confused. 😅
> 
> To your question: I would say the user wants to enter his own issues. But that's not happening in this screen. It might be a future step.

Yeah I also think the same way that I will come later on.

**Comment by Sukhpreet92** [comment]
> Now I'm also a bit confused. 😅
> 
> To your question: I would say the user wants to enter his own issues. But that's not happening in this screen. It might be a future step.

if you have the time please check again if looks fine

**Comment by gacsphere** [comment]
Hi Sukhpreet,

this looks very good, it's only a bit too much for the first user story. You can make it three or four user stories:
1. display list of habits (no buttons yet)
2. add delete button to delete single habits
3. add add-button to add more habits
4. add form to enter further habits

Maybe my suggestions for issue 3 and 4 don't need to be two issues but could be combined in one.

**Comment by F-Kirchhoff** [comment]
Hey, this is a better start, do you plan to code all CRUD operations in one user story? This might be too much. If some buttons like the add button are not functional at the moment, leave it out and add it with the next user story.

**Comment by Sukhpreet92** [comment]
> Hi Sukhpreet,
> 
> this looks very good, it's only a bit too much for the first user story. You can make it three or four user stories:
> 
> 1. display list of habits (no buttons yet)
> 2. add delete button to delete single habits
> 3. add add-button to add more habits
> 4. add form to enter further habits
> 
> Maybe my suggestions for issue 3 and 4 don't need to be two issues but could be combined in one.

Thank you Gesa I will separate them in different user stories

**Comment by Sukhpreet92** [comment]
> Hey, this is a better start, do you plan to code all CRUD operations in one user story? This might be too much. If some buttons like the add button are not functional at the moment, leave it out and add it with the next user story.

Thank you I will do so.
