### ISSUE TITLE
Create Searchbar

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#20]
## Value Proposition
As a user, I want search for my habit so that I can easily find them .
## Description
![Screenshot 2022-11-02 at 12 06 32](https://user-images.githubusercontent.com/111757889/199477173-8d95ef69-1e93-4c5b-985a-256873e13c68.png)

![Screenshot 2022-11-02 at 12 09 15](https://user-images.githubusercontent.com/111757889/199474894-56431b12-e20e-433c-b7e5-753299b2e690.png)
ec59d.png)

## Acception Criteria
- [ ] create search-bar
- [ ] able to search the habits
## Tasks
- [ ] create new branch `search-bar`
- [ ] add `searchIcon` to the images folder
- [ ] import searchIcon to Navigation.js
- [ ] create search component 
- [ ] import DB to the component
- [ ] create `Input` box
