### ISSUE TITLE
add input box and add button

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#3]
## Value Proposition
As a User I should be able to add my habit to the list, 
I want to have an form
so that I can enter my habit.

## Description
![Screenshot 2022-10-17 at 16 29 55](https://user-images.githubusercontent.com/111757889/196204204-6a846674-8913-4df6-86cd-88848a981f17.png)

## Acception Criteria
- [x] create a form 
- [x] create an add button

## Tasks
- [x] create new branch called `form`
- [x]  Create a form with required input field and a submit button.
- [x] user can click on add button to display the habit in the list above
- [x] Write a submit-function, which renders the input data.
- [x] create button component

**Comment by AHen-C0de** [comment]
Please add how the new habit is rendered in your list. Do you have a useState that is updated?

**Comment by philmetscher** [comment]
"As a I should be able to add my own habit" - As a what? 😄

**Comment by philmetscher** [comment]
Do you use Input as a Component? Then you could write something like "add `Input component`". Same thing for the Button
