### ISSUE TITLE
Add delete function

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#4]
## Value Proposition
As a user
 I want to delete my habits 
so that I discard habits I don't want anymore

## Description

![Screenshot 2022-10-17 at 11 34 06](https://user-images.githubusercontent.com/111757889/196272161-333baef5-d93b-46e0-af66-ff99fd506d9f.png)

## Acception Criteria
- [ ] next to the habit, there is a trash icon on the delete button, 
- [ ] by clicking on the icon, the entered habit will delete from localStorage

## Tasks
- [x] Create new branch
- [x]  add Button component (delete) with the Icon component (trash-icon) to every created habit
- [x] write delete function for the button

**Comment by philmetscher** [comment]
Hey nice short user-story 👍 **Some Feedback**
You should implement the delete-button first and then write a function for it :)
If you use a `Button component` & `Icon component` in Task 3 you could write:
"add `Button component` (delete) with the `Icon component` (trash-icon) to every created habit".

**Comment by sebsch1337** [comment]
Looks good. Just to understand :) What means "habit will disappear"? Maybe you could specify the delete function a bit more? Will it remove the item data from a state or localStorage?

**Comment by Sukhpreet92** [comment]
> Hey nice short user-story 👍 **Some Feedback** You should implement the delete-button first and then write a function for it :) If you use a `Button component` & `Icon component` in Task 3 you could write: "add `Button component` (delete) with the `Icon component` (trash-icon) to every created habit".

Thank you phil 
it is quite difficult for me to understand this user story concept 😓. i will use your tips.

**Comment by Sukhpreet92** [comment]
> Looks good. Just to understand :) What means "habit will disappear"? Maybe you could specify the delete function a bit more? Will it remove the item data from a state or localStorage?

i will try that 😓
