### ISSUE TITLE
Create a done button 

### ISSUE THREAD

**Issue by Sukhpreet92** [Sukhpreet92/capstone-project#7]
## Value Proposition
As a user,
I want to mark my habit as done
so that i can see which ones I've already done.

## Description

![Screenshot 2022-10-18 at 23 12 40](https://user-images.githubusercontent.com/111757889/196545931-374041a2-29d0-49b4-9de9-821e64749f14.png)

## Acception Criteria
- [x] as a user i want to have a check button on the right side, next to the trash icon 
- [x] as a user i can see my tasks can be marked and unmarked 
- [x] marked tasks will be shown at the end of the list 

## Tasks
- [x] create a new branch for this feature 
- [x] create a check button component 
- [x] work with useState to have a state variables
- [x] create a if-function onCheck(able to disable and able the button)
- [x] add styled.component to the button

**Comment by Roland-Hufnagel** [comment]
It is a nice and short userstory but I think it is a good idea, to make the tasks a bit more detailed, e.g. what is the useState used for and what does the function onCheck has to do.

**Comment by Sukhpreet92** [comment]
> It is a nice and short userstory but I think it is a good idea, to make the tasks a bit more detailed, e.g. what is the useState used for and what does the function onCheck has to do.

thank you i made the changes
